### ISSUE TITLE
ServiceMatrix failures when on slow/spotty internet connection

### ISSUE THREAD

**Issue by dprothero** [Particular/ServiceMatrix#425]
When on a poor/spotty internet connection (like the wi-fi on an airplane), ServiceMatrix frequently crashes when trying to create a new NSB V5 project:

![image](https://cloud.githubusercontent.com/assets/1897006/4576522/eeb3c84c-4fb3-11e4-938b-cf8b1b6844af.png)

Or, many times you will get the following message with the associated exception text in the log:

![image](https://cloud.githubusercontent.com/assets/1897006/4576530/0c805b74-4fb4-11e4-86aa-e0ffd5d0710e.png)

NuPattern.Library.Automation.EventAutomation Error: 0 : Event automation 'OnInstantiated' failed.
System.Exception: NuGet Package NServiceBus cannot be installed (Unable to find package 'NServiceBus'.). ---> System.InvalidOperationException: Unable to find package 'NServiceBus'.
   at NuGet.PackageRepositoryHelper.ResolvePackage(IPackageRepository sourceRepository, IPackageRepository localRepository, IPackageConstraintProvider constraintProvider, String packageId, SemanticVersion version, Boolean allowPrereleaseVersions)
   at NuGet.VisualStudio.VsPackageManager.InstallPackage(IProjectManager projectManager, String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean allowPrereleaseVersions, Boolean skipAssemblyReferences, ILogger logger)
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(IPackageRepository repository, Project project, String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean skipAssemblyReferences)
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, SemanticVersion version, Boolean ignoreDependencies)
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at NServiceBusStudio.Automation.Extensions.SolutionExtensions.InstallLatestNugetPackage(IProject project, IVsPackageInstallerServices vsPackageInstallerServices, IVsPackageInstaller vsPackageInstaller, String packageId, Nullable`1 majorVersion)
   at NServiceBusStudio.Automation.Extensions.SolutionExtensions.InstallNuGetPackage(IProject project, IVsPackageInstallerServices vsPackageInstallerServices, IVsPackageInstaller vsPackageInstaller, IStatusBar StatusBar, String packageName, String targetNsbVersion)
   --- End of inner exception stack trace ---
   at NServiceBusStudio.Automation.Extensions.SolutionExtensions.InstallNuGetPackage(IProject project, IVsPackageInstallerServices vsPackageInstallerServices, IVsPackageInstaller vsPackageInstaller, IStatusBar StatusBar, String packageName, String targetNsbVersion)
   at NServiceBusStudio.Automation.Commands.AddInfrastructureProjectReferences.Execute()
   at NuPattern.Library.Automation.CommandAutomation.Execute(IDynamicBindingContext context, Boolean withAutomation)
   at NuPattern.Library.Automation.CommandAutomation.Execute()
   at NuPattern.Library.Commands.AggregatorCommand.Execute()
   at NuPattern.Library.Automation.CommandAutomation.Execute(IDynamicBindingContext context, Boolean withAutomation)
   at NuPattern.Library.Automation.CommandAutomation.Execute()
   at NuPattern.Library.Automation.EventAutomation.ExecuteCommand()
   at NuPattern.Library.Automation.EventAutomation.<>c__DisplayClassd.<Execute>b__a()
   at NuPattern.VisualStudio.TraceSourceExtensions.DoShield(ITracer traceSource, Action action, String format, Boolean showUI, String[] args)

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
