### ISSUE TITLE
NuPattern.Library.Automation.EventAutomation Error: 0 : Event automation 'OnInstantiated' failed.

### ISSUE THREAD

**Issue by kamabery** [Particular/ServiceMatrix#443]
I didn't get any errors installing, however when creating a new NServiceBus v5 System I get the following error: 
```
NuPattern.Library.Automation.EventAutomation Error: 0 : Event automation 'OnInstantiated' failed.
System.Exception: NuGet Package NServiceBus cannot be installed (Error: Missing method 'instance string [Particular.ServiceMatrix.Automation] NuGet.VisualStudio.IVsPackageMetadata::get_VersionString()' from class 'NuGet.VisualStudio.VsPackageMetadata'.). ---> System.MissingMethodException: Error: Missing method 'instance string [Particular.ServiceMatrix.Automation] NuGet.VisualStudio.IVsPackageMetadata::get_VersionString()' from class 'NuGet.VisualStudio.VsPackageMetadata'.
   at NuGet.VisualStudio.IVsPackageMetadata.get_VersionString()
   at NServiceBusStudio.Automation.Extensions.NugetPackageVersionManager.UpdateCache(String packageId, Nullable`1 majorVersion, IEnumerable`1 installedPackages)
   at NServiceBusStudio.Automation.Extensions.SolutionExtensions.InstallLatestNugetPackage(IProject project, IVsPackageInstallerServices vsPackageInstallerServices, IVsPackageInstaller vsPackageInstaller, String packageId, Nullable`1 majorVersion)
   at NServiceBusStudio.Automation.Extensions.SolutionExtensions.InstallNuGetPackage(IProject project, IVsPackageInstallerServices vsPackageInstallerServices, IVsPackageInstaller vsPackageInstaller, IStatusBar StatusBar, String packageName, String targetNsbVersion)
   --- End of inner exception stack trace ---
   at NServiceBusStudio.Automation.Extensions.SolutionExtensions.InstallNuGetPackage(IProject project, IVsPackageInstallerServices vsPackageInstallerServices, IVsPackageInstaller vsPackageInstaller, IStatusBar StatusBar, String packageName, String targetNsbVersion)
   at NServiceBusStudio.Automation.Commands.AddInfrastructureProjectReferences.Execute()
   at NuPattern.Library.Automation.CommandAutomation.Execute(IDynamicBindingContext context, Boolean withAutomation)
   at NuPattern.Library.Automation.CommandAutomation.Execute()
   at NuPattern.Library.Commands.AggregatorCommand.Execute()
   at NuPattern.Library.Automation.CommandAutomation.Execute(IDynamicBindingContext context, Boolean withAutomation)
   at NuPattern.Library.Automation.CommandAutomation.Execute()
   at NuPattern.Library.Automation.EventAutomation.ExecuteCommand()
   at NuPattern.Library.Automation.EventAutomation.<>c__DisplayClassd.<Execute>b__a()
   at NuPattern.VisualStudio.TraceSourceExtensions.DoShield(ITracer traceSource, Action action, String format, Boolean showUI, String[] args)
NuPattern.Library.Automation.EventAutomation Error: 0 : Event automation 'OnInstantiated' failed.
System.Exception: NuGet Package NServiceBus cannot be installed (Error: Missing method 'instance string [Particular.ServiceMatrix.Automation] NuGet.VisualStudio.IVsPackageMetadata::get_VersionString()' from class 'NuGet.VisualStudio.VsPackageMetadata'.). ---> System.MissingMethodException: Error: Missing method 'instance string [Particular.ServiceMatrix.Automation] NuGet.VisualStudio.IVsPackageMetadata::get_VersionString()' from class 'NuGet.VisualStudio.VsPackageMetadata'.
   at NuGet.VisualStudio.IVsPackageMetadata.get_VersionString()
   at NServiceBusStudio.Automation.Extensions.NugetPackageVersionManager.UpdateCache(String packageId, Nullable`1 majorVersion, IEnumerable`1 installedPackages)
   at NServiceBusStudio.Automation.Extensions.SolutionExtensions.InstallLatestNugetPackage(IProject project, IVsPackageInstallerServices vsPackageInstallerServices, IVsPackageInstaller vsPackageInstaller, String packageId, Nullable`1 majorVersion)
   at NServiceBusStudio.Automation.Extensions.SolutionExtensions.InstallNuGetPackage(IProject project, IVsPackageInstallerServices vsPackageInstallerServices, IVsPackageInstaller vsPackageInstaller, IStatusBar StatusBar, String packageName, String targetNsbVersion)
   --- End of inner exception stack trace ---
   at NServiceBusStudio.Automation.Extensions.SolutionExtensions.InstallNuGetPackage(IProject project, IVsPackageInstallerServices vsPackageInstallerServices, IVsPackageInstaller vsPackageInstaller, IStatusBar StatusBar, String packageName, String targetNsbVersion)
   at NServiceBusStudio.Automation.Commands.AddInfrastructureProjectReferences.Execute()
   at NuPattern.Library.Automation.CommandAutomation.Execute(IDynamicBindingContext context, Boolean withAutomation)
   at NuPattern.Library.Automation.CommandAutomation.Execute()
   at NuPattern.Library.Commands.AggregatorCommand.Execute()
   at NuPattern.Library.Automation.CommandAutomation.Execute(IDynamicBindingContext context, Boolean withAutomation)
   at NuPattern.Library.Automation.CommandAutomation.Execute()
   at NuPattern.Library.Automation.EventAutomation.ExecuteCommand()
   at NuPattern.Library.Automation.EventAutomation.<>c__DisplayClassd.<Execute>b__a()
   at NuPattern.VisualStudio.TraceSourceExtensions.DoShield(ITracer traceSource, Action action, String format, Boolean showUI, String[] args)
```

**Comment by indualagarsamy** [comment]
can you try updating to the latest Nuget version on VS and retry?

**Comment by kamabery** [comment]
PM> Install-package NServiceBus
'NServiceBus 5.2.0' already installed.
TestBus1.Contracts already has a reference to 'NServiceBus 5.2.0'.  

I originally installed using  the Platform Installer

**Comment by indualagarsamy** [comment]
@kamabery - what is the version of Nuget Package Manager are you currently using in your Visual Studio? I believe SM requires a version atleast 2.8.1 or greater. If you are using an older version, can you try updating the Nuget Package Manager and retry?

**Comment by kamabery** [comment]
That did the trick! Thanks!!
